version: "3.3"

services:

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=**youremail@here.com**"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.filename=/etc/traefik/dyn-conf.yml"
      - "--serverstransport.insecureskipverify=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.**yourdomain**`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.dashboard.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.dashboard-secured.rule=Host(`traefik.**yourdomain**`)"
      - "traefik.http.routers.dashboard-secured.entrypoints=web-secure"
      - "traefik.http.routers.dashboard-secured.tls=true"
      - "traefik.http.routers.dashboard-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.authtraefik.basicauth.users=admin:**pwhash**"
      - "traefik.http.routers.dashboard-secured.middlewares=authtraefik"
    expose:
      - 8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./dyn-conf.yml:/etc/traefik/dyn-conf.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

